# Generated by Django 4.2.7 on 2026-01-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0014_alter_proschet_circulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VichisliniyaListovModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vichisliniya_listov_list_count', models.DecimalField(decimal_places=2, default=0.0, help_text='Расчётное количество листов на основе тиража и других параметров', max_digits=10, verbose_name='Количество листов')),
                ('vichisliniya_listov_vyleta', models.PositiveIntegerField(default=1, help_text='Количество дополнительных листов на обрезку и возможный брак', verbose_name='Вылеты')),
                ('vichisliniya_listov_polosa_count', models.PositiveIntegerField(default=1, help_text='Количество полос (страниц), размещаемых на одном листе', verbose_name='Количество полос')),
                ('vichisliniya_listov_color', models.CharField(choices=[('1+0', '1+0 (односторонняя одноцветная)'), ('1+1', '1+1 (двусторонняя одноцветная)'), ('4+0', '4+0 (односторонняя полноцветная)'), ('4+4', '4+4 (двусторонняя полноцветная)')], default='4+0', help_text='Вариант цветности печати', max_length=10, verbose_name='Цветность')),
                ('vichisliniya_listov_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('vichisliniya_listov_updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('vichisliniya_listov_print_component', models.ForeignKey(help_text='Печатный компонент, для которого выполняются вычисления листов', on_delete=django.db.models.deletion.CASCADE, related_name='vichisliniya_listov_data', to='calculator.printcomponent', unique=True, verbose_name='Печатный компонент')),
            ],
            options={
                'verbose_name': 'Вычисление листов',
                'verbose_name_plural': 'Вычисления листов',
                'db_table': 'vichisliniya_listov_data',
                'ordering': ['-vichisliniya_listov_created_at'],
            },
        ),
    ]
