# Generated by Django 4.2.7 on 2026-02-24 21:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_fit_horizontal',
            field=models.PositiveIntegerField(default=0, help_text='Количество изделий, помещающихся по горизонтали при текущей выбранной ориентации', verbose_name='По горизонтали'),
        ),
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_fit_landscape_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество изделий, если размещать их в альбомной ориентации (без поворота)', verbose_name='Альбомная ориентация'),
        ),
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_fit_portrait_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество изделий, если размещать их в портретной ориентации (с поворотом на 90°)', verbose_name='Портретная ориентация'),
        ),
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_fit_selected_orientation',
            field=models.CharField(choices=[('landscape', 'Альбомная'), ('portrait', 'Портретная'), ('auto', 'Авто (оптимальная)')], default='auto', help_text='Какая ориентация размещения выбрана в данный момент', max_length=10, verbose_name='Выбранная ориентация'),
        ),
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_fit_total',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество изделий, помещающихся на одном листе при выбранной ориентации', verbose_name='Всего изделий на листе'),
        ),
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_fit_vertical',
            field=models.PositiveIntegerField(default=0, help_text='Количество изделий, помещающихся по вертикали при текущей выбранной ориентации', verbose_name='По вертикали'),
        ),
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_item_height',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Высота одного изделия в миллиметрах (например, 50 для визитки)', max_digits=6, verbose_name='Высота изделия (мм)'),
        ),
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_item_width',
            field=models.DecimalField(decimal_places=2, default=Decimal('90.00'), help_text='Ширина одного изделия в миллиметрах (например, 90 для визитки)', max_digits=6, verbose_name='Ширина изделия (мм)'),
        ),
        migrations.AlterField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_polosa_count',
            field=models.PositiveIntegerField(default=1, help_text='Количество полос (страниц), размещаемых на одном листе (устаревает)', verbose_name='Количество полос'),
        ),
        migrations.AlterField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_vyleta',
            field=models.PositiveIntegerField(default=1, help_text='Расстояние между изделиями на листе в миллиметрах (используется для расчёта размещения)', verbose_name='Вылеты (межвизиточное расстояние)'),
        ),
    ]
