# Generated by Django 4.2.7 on 2026-02-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0002_vichisliniyalistovmodel_vichisliniya_listov_fit_horizontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_list_count',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Расчётное количество листов на основе тиража и количества изделий на листе (округлено вверх)', max_digits=10, verbose_name='Количество листов'),
        ),
    ]
