# Generated by Django 4.2.7 on 2026-03-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0003_alter_vichisliniyalistovmodel_vichisliniya_listov_list_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_cuts_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество резов для разделения листа на изделия: (количество по горизонтали + 1) + (количество по вертикали + 1)', verbose_name='Количество резов'),
        ),
    ]
