# Generated by Django 4.2.7 on 2026-03-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0028_alter_additionalwork_price_and_more'),
        ('vichisliniya_listov', '0004_vichisliniyalistovmodel_vichisliniya_listov_cuts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vichisliniyalistovmodel',
            name='vichisliniya_listov_print_component',
            field=models.OneToOneField(help_text='Печатный компонент, для которого выполняются вычисления листов (один компонент – одна запись)', on_delete=django.db.models.deletion.CASCADE, related_name='vichisliniya_listov_data', to='calculator.printcomponent', verbose_name='Печатный компонент'),
        ),
    ]
