# Generated by Django 4.2.7 on 2026-04-05 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0039_printcomponent_print_type_and_more'),
        ('vichisliniya_listov', '0005_alter_vichisliniyalistovmodel_vichisliniya_listov_print_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipageBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: скрепка, пружина, КБС', max_length=50, unique=True, verbose_name='Название')),
                ('page_multiple', models.PositiveSmallIntegerField(help_text='Количество страниц должно быть кратно этому числу. Для скрепки = 4, для пружины = 2, для КБС = 2', verbose_name='Кратность страниц')),
                ('paper_coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Коэффициент, учитывающий дополнительный расход бумаги (например, на обложку)', max_digits=5, verbose_name='Коэффициент бумаги')),
                ('description', models.TextField(blank=True, help_text='Подробное описание технологии скрепления', verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Способ скрепления (многостраничное)',
                'verbose_name_plural': 'Способы скрепления (многостраничное)',
                'db_table': 'vichisliniya_listov_multipage_bindings',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VichisliniyaMultipageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.PositiveIntegerField(default=4, help_text='Общее количество страниц в готовом изделии', verbose_name='Количество страниц')),
                ('pages_per_sheet', models.PositiveSmallIntegerField(default=4, help_text='Количество страниц, которое печатается на одном физическом листе (с обеих сторон)', verbose_name='Страниц на листе')),
                ('sheet_count', models.DecimalField(decimal_places=2, default=0.0, help_text='Расчётное количество печатных листов на тираж', max_digits=10, verbose_name='Количество печатных листов')),
                ('copies', models.PositiveIntegerField(default=1, help_text='Количество готовых брошюр (обычно равно тиражу просчёта)', verbose_name='Количество экземпляров')),
                ('finished_width', models.DecimalField(decimal_places=2, default=210.0, help_text='Ширина готовой брошюры в миллиметрах', max_digits=6, verbose_name='Ширина готового изделия (мм)')),
                ('finished_height', models.DecimalField(decimal_places=2, default=297.0, help_text='Высота готовой брошюры в миллиметрах', max_digits=6, verbose_name='Высота готового изделия (мм)')),
                ('color', models.CharField(choices=[('1+0', '1+0 (односторонняя одноцветная)'), ('1+1', '1+1 (двусторонняя одноцветная)'), ('4+0', '4+0 (односторонняя полноцветная)'), ('4+4', '4+4 (двусторонняя полноцветная)')], default='4+0', max_length=10, verbose_name='Цветность')),
                ('vyleta', models.PositiveIntegerField(default=1, help_text='Расстояние между отпечатками страниц на листе', verbose_name='Вылеты (мм)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('binding', models.ForeignKey(blank=True, help_text='Как будет скреплена брошюра: скрепка, пружина, КБС', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vichisliniya_listov.multipagebinding', verbose_name='Способ скрепления')),
                ('print_component', models.OneToOneField(help_text='Печатный компонент, для которого выполняются многостраничные вычисления', on_delete=django.db.models.deletion.CASCADE, related_name='multipage_data', to='calculator.printcomponent', verbose_name='Печатный компонент')),
            ],
            options={
                'verbose_name': 'Многостраничное вычисление',
                'verbose_name_plural': 'Многостраничные вычисления',
                'db_table': 'vichisliniya_listov_multipage_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
