# Generated by Django 4.2.7 on 2026-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0006_multipagebinding_vichisliniyamultipagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vichisliniyamultipagemodel',
            name='pages_per_sheet',
        ),
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='fit_horizontal',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц, помещающихся по горизонтали при текущей выбранной ориентации', verbose_name='По горизонтали'),
        ),
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='fit_landscape_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц, если размещать их в альбомной ориентации (без поворота)', verbose_name='Альбомная ориентация'),
        ),
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='fit_portrait_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц, если размещать их в портретной ориентации (с поворотом на 90°)', verbose_name='Портретная ориентация'),
        ),
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='fit_selected_orientation',
            field=models.CharField(choices=[('landscape', 'Альбомная'), ('portrait', 'Портретная'), ('auto', 'Авто (оптимальная)')], default='auto', help_text='Какая ориентация размещения выбрана в данный момент', max_length=10, verbose_name='Выбранная ориентация'),
        ),
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='fit_total',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество страниц, помещающихся на одном листе при выбранной ориентации', verbose_name='Всего страниц на листе'),
        ),
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='fit_vertical',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц, помещающихся по вертикали при текущей выбранной ориентации', verbose_name='По вертикали'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='finished_height',
            field=models.DecimalField(decimal_places=2, default=297.0, help_text='Высота одной страницы в миллиметрах (например, 297 для A4)', max_digits=6, verbose_name='Высота страницы (мм)'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='finished_width',
            field=models.DecimalField(decimal_places=2, default=210.0, help_text='Ширина одной страницы в миллиметрах (например, 210 для A4)', max_digits=6, verbose_name='Ширина страницы (мм)'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='sheet_count',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Расчётное количество печатных листов на тираж (с округлением вверх)', max_digits=10, verbose_name='Количество печатных листов'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='vyleta',
            field=models.PositiveIntegerField(default=1, help_text='Расстояние между страницами на листе в миллиметрах', verbose_name='Вылеты (зазор) (мм)'),
        ),
    ]
