# Generated by Django 4.2.7 on 2026-04-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0007_remove_vichisliniyamultipagemodel_pages_per_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipagebinding',
            name='booklet_orientation',
            field=models.CharField(choices=[('portrait', 'Вертикальная'), ('landscape', 'Горизонтальная')], default='portrait', help_text='Ориентация готовой брошюры (влияет на размещение разворотов)', max_length=10, verbose_name='Ориентация брошюры'),
        ),
    ]
