# Generated by Django 4.2.7 on 2026-04-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0008_multipagebinding_booklet_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipagebinding',
            name='booklet_orientation',
        ),
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='booklet_orientation',
            field=models.CharField(choices=[('portrait', 'Вертикальная (портретная)'), ('landscape', 'Горизонтальная (альбомная)')], default='portrait', help_text='Вертикальная (портретная) или горизонтальная (альбомная) ориентация готовой брошюры. Влияет на то, как развороты размещаются на листе: для вертикальной – две страницы рядом, для горизонтальной – одна над другой.', max_length=10, verbose_name='Ориентация брошюры'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_horizontal',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц/разворотов, помещающихся по горизонтали при текущей выбранной ориентации', verbose_name='По горизонтали'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_landscape_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц/разворотов, если размещать их в альбомной ориентации (без поворота)', verbose_name='Альбомная ориентация'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_portrait_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц/разворотов, если размещать их в портретной ориентации (с поворотом на 90°)', verbose_name='Портретная ориентация'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_selected_orientation',
            field=models.CharField(choices=[('landscape', 'Альбомная'), ('portrait', 'Портретная'), ('auto', 'Авто (оптимальная)')], default='auto', help_text='Какая ориентация размещения выбрана в данный момент (для способов, отличных от скрепки)', max_length=10, verbose_name='Выбранная ориентация'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_vertical',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц/разворотов, помещающихся по вертикали при текущей выбранной ориентации', verbose_name='По вертикали'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='sheet_count',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Расчётное количество печатных листов на тираж (с округлением вверх) – уже с учётом тиража', max_digits=10, verbose_name='Количество печатных листов'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='vyleta',
            field=models.PositiveIntegerField(default=1, help_text='Расстояние между страницами/разворотами на листе в миллиметрах', verbose_name='Вылеты (зазор) (мм)'),
        ),
    ]
