# Generated by Django 4.2.7 on 2026-04-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0009_remove_multipagebinding_booklet_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vichisliniyamultipagemodel',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Определяет, выбран ли многостраничный режим для этого компонента. Если False – используется одностраничный режим.', verbose_name='Многостраничный режим активен'),
        ),
    ]
