# Generated by Django 4.2.7 on 2026-09-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vichisliniya_listov', '0010_vichisliniyamultipagemodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='booklet_orientation',
            field=models.CharField(choices=[('portrait', 'Вертикальная (портретная)'), ('landscape', 'Горизонтальная (альбомная)')], default='portrait', help_text='Вертикальная (портретная) или горизонтальная (альбомная) ориентация готовой брошюры. Влияет на то, как развороты размещаются на листе.', max_length=10, verbose_name='Ориентация брошюры'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_horizontal',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц/разворотов, помещающихся по горизонтали на одной стороне листа', verbose_name='По горизонтали (на одной стороне)'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_landscape_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц на одной стороне, если размещать их в альбомной ориентации (без поворота)', verbose_name='Альбомная ориентация (на одной стороне)'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_portrait_total',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц на одной стороне, если размещать их в портретной ориентации (с поворотом на 90°)', verbose_name='Портретная ориентация (на одной стороне)'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_total',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество страниц, помещающихся на ОДНОЙ стороне листа при выбранной ориентации', verbose_name='Всего страниц на одной стороне листа'),
        ),
        migrations.AlterField(
            model_name='vichisliniyamultipagemodel',
            name='fit_vertical',
            field=models.PositiveIntegerField(default=0, help_text='Количество страниц/разворотов, помещающихся по вертикали на одной стороне листа', verbose_name='По вертикали (на одной стороне)'),
        ),
    ]
