# Generated by Django 4.2.7 on 2026-09-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0010_work_cost_work_markup_percent_alter_work_k_lines_and_more'),
        ('vichisliniya_listov', '0011_alter_vichisliniyamultipagemodel_booklet_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipagebinding',
            name='default_work',
            field=models.ForeignKey(blank=True, help_text='Работа, которая автоматически добавляется к компоненту-обложке при выборе этого скрепления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindings_as_default', to='spravochnik_dopolnitelnyh_rabot.work', verbose_name='Работа по умолчанию'),
        ),
    ]
