# Generated by Django 4.2.7 on 2025-12-24 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheet_formats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите уникальное название принтера', max_length=200, unique=True, verbose_name='Название принтера')),
                ('margin_mm', models.IntegerField(default=5, help_text='Размер незапечатываемых полей листа в миллиметрах', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Поля (мм)')),
                ('duplex_coefficient', models.FloatField(default=2.0, help_text='Коэффициент увеличения при двусторонней печати', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Коэффициент двусторонней печати')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sheet_format', models.ForeignKey(help_text='Выберите формат листа из списка созданных форматов', on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='sheet_formats.sheetformat', verbose_name='Формат листа')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='devices_pri_name_6355a9_idx'), models.Index(fields=['sheet_format'], name='devices_pri_sheet_f_8fe665_idx'), models.Index(fields=['created_at'], name='devices_pri_created_0acbda_idx')],
            },
        ),
    ]
