# Generated by Django 4.2.7 on 2025-12-21 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название принтера (например, "RICOH Pro C7200S")', max_length=200, unique=True, verbose_name='Название принтера')),
                ('sheet_format', models.CharField(help_text='Введите обозначение формата (например, "SRA3", "A4", "A3+")', max_length=50, verbose_name='Формат листа')),
                ('width_mm', models.IntegerField(help_text='Введите ширину листа в миллиметрах (например, 320)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ширина (мм)')),
                ('height_mm', models.IntegerField(help_text='Введите высоту листа в миллиметрах (например, 450)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота (мм)')),
                ('margin_mm', models.IntegerField(default=5, help_text='Введите размер незапечатываемых полей листа в миллиметрах (обычно 5)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Поля (мм)')),
                ('duplex_coefficient', models.FloatField(default=2.0, help_text='Введите коэффициент увеличения при двусторонней печати (обычно 2.0)', validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Коэффициент двусторонней печати')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='devices_pri_name_6355a9_idx'), models.Index(fields=['sheet_format'], name='devices_pri_sheet_f_2d8ac9_idx')],
            },
        ),
    ]
