# Generated by Django 4.2.7 on 2026-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='devices_interpolation_method',
            field=models.CharField(choices=[('linear', 'Линейная интерполяция'), ('logarithmic', 'Логарифмическая интерполяция')], default='linear', help_text='Выберите метод интерполяции для расчета стоимости при произвольном тираже', max_length=20, verbose_name='Метод интерполяции'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['devices_interpolation_method'], name='devices_pri_devices_87aa18_idx'),
        ),
    ]
