# Generated by Django 4.2.7 on 2026-03-30 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_formats', '0001_initial'),
        ('devices', '0002_printer_devices_interpolation_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='devices_interpolation_method',
            field=models.CharField(choices=[('linear', 'Линейная интерполяция'), ('logarithmic', 'Логарифмическая интерполяция')], default='linear', help_text='Выберите метод интерполяции для расчёта стоимости при произвольном тираже', max_length=20, verbose_name='Метод интерполяции'),
        ),
        migrations.CreateModel(
            name='Laminator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите уникальное название ламинатора', max_length=200, unique=True, verbose_name='Название ламинатора')),
                ('margin_mm', models.IntegerField(default=5, help_text='Размер незапечатываемых полей листа в миллиметрах', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Поля (мм)')),
                ('duplex_coefficient', models.FloatField(default=2.0, help_text='Коэффициент для двусторонней ламинации', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Коэффициент')),
                ('laminator_interpolation_method', models.CharField(choices=[('linear', 'Линейная интерполяция'), ('logarithmic', 'Логарифмическая интерполяция')], default='linear', help_text='Выберите метод интерполяции для расчёта стоимости при произвольном тираже', max_length=20, verbose_name='Метод интерполяции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sheet_format', models.ForeignKey(help_text='Выберите формат листа из списка созданных форматов', on_delete=django.db.models.deletion.PROTECT, related_name='laminators', to='sheet_formats.sheetformat', verbose_name='Формат листа')),
            ],
            options={
                'verbose_name': 'Ламинатор',
                'verbose_name_plural': 'Ламинаторы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='devices_lam_name_1ee899_idx'), models.Index(fields=['sheet_format'], name='devices_lam_sheet_f_93a181_idx'), models.Index(fields=['created_at'], name='devices_lam_created_0c56a2_idx'), models.Index(fields=['laminator_interpolation_method'], name='devices_lam_laminat_acf5c5_idx')],
            },
        ),
    ]
