# Generated by Django 4.2.7 on 2026-03-01 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование дополнительной работы', max_length=255, verbose_name='Название работы')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость работы в рублях (можно копейки)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дополнительная работа',
                'verbose_name_plural': 'Дополнительные работы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='spravochnik_name_96620b_idx'), models.Index(fields=['created_at'], name='spravochnik_created_4e9f54_idx')],
            },
        ),
    ]
