# Generated by Django 4.2.7 on 2026-03-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='default_items_per_sheet',
            field=models.PositiveIntegerField(default=1, help_text='Используется для формул, где требуется количество изделий на листе. Можно изменить при добавлении работы.', verbose_name='Количество изделий на листе (по умолчанию)'),
        ),
        migrations.AddField(
            model_name='work',
            name='default_lines_count',
            field=models.PositiveIntegerField(default=1, help_text='Используется для формул, где требуется количество линий реза. Можно изменить при добавлении работы.', verbose_name='Количество линий реза (по умолчанию)'),
        ),
        migrations.AddField(
            model_name='work',
            name='formula_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена'), (3, 'Тираж × Цена × Количество линий реза'), (4, 'Количество листов × Цена × Количество линий реза'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, help_text='Выберите формулу, по которой будет вычисляться стоимость этой работы при добавлении в просчёт.', verbose_name='Формула расчёта'),
        ),
    ]
