# Generated by Django 4.2.7 on 2026-03-07 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0002_work_default_items_per_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='interpolation_method',
            field=models.CharField(choices=[('linear', 'Линейная'), ('logarithmic', 'Логарифмическая')], default='linear', help_text='Способ расчёта цены для произвольного количества листов между опорными точками', max_length=20, verbose_name='Метод интерполяции цены'),
        ),
        migrations.AlterField(
            model_name='work',
            name='default_items_per_sheet',
            field=models.PositiveIntegerField(default=1, help_text='Используется для формул, где требуется количество изделий на листе', verbose_name='Количество изделий на листе (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='default_lines_count',
            field=models.PositiveIntegerField(default=1, help_text='Используется для формул, где требуется количество линий реза', verbose_name='Количество линий реза (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='formula_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена'), (3, 'Тираж × Цена × Количество линий реза'), (4, 'Количество листов × Цена × Количество линий реза'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, help_text='Выберите формулу для вычисления стоимости', verbose_name='Формула расчёта'),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Базовая цена (может быть интерполирована при расчёте)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб)'),
        ),
        migrations.CreateModel(
            name='WorkPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheets', models.PositiveIntegerField(help_text='Введите количество листов для опорной точки', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество листов')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена работы при данном количестве листов', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_prices', to='spravochnik_dopolnitelnyh_rabot.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Цена работы за листы',
                'verbose_name_plural': 'Цены работы за листы',
                'ordering': ['work', 'sheets'],
                'indexes': [models.Index(fields=['work'], name='spravochnik_work_id_41d525_idx'), models.Index(fields=['sheets'], name='spravochnik_sheets_9d1594_idx')],
                'unique_together': {('work', 'sheets')},
            },
        ),
    ]
