# Generated by Django 4.2.7 on 2026-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0003_work_interpolation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='k_lines',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Коэффициент, усиливающий влияние количества резов в формуле 4. Чем больше, тем сильнее влияние.', max_digits=5, verbose_name='Коэффициент резов'),
        ),
    ]
