# Generated by Django 4.2.7 on 2026-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0004_work_k_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='k_lines',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Коэффициент, усиливающий влияние количества резов в формуле 4. Чем больше, тем сильнее влияние.', max_digits=5, verbose_name='Коэффициент резов'),
        ),
    ]
