# Generated by Django 4.2.7 on 2026-03-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0006_alter_work_k_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='formula_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена'), (3, 'Цена × Количество листов × (Количество резов × Коэффициент)'), (4, 'Количество листов × Цена × Количество резов (логарифмическая)'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, help_text='Выберите формулу для вычисления стоимости', verbose_name='Формула расчёта'),
        ),
    ]
