# Generated by Django 4.2.7 on 2026-03-14 22:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0007_alter_work_formula_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='formula_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена'), (3, 'Цена × Тираж × (Количество резов × Коэффициент)'), (4, 'Количество листов × Цена × Количество резов (логарифмическая)'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, help_text='Выберите формулу для вычисления стоимости', verbose_name='Формула расчёта'),
        ),
        migrations.CreateModel(
            name='WorkCirculationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.PositiveIntegerField(help_text='Количество экземпляров (тираж) для опорной точки', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тираж')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Цена работы при данном тираже', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulation_prices', to='spravochnik_dopolnitelnyh_rabot.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Цена работы за тираж',
                'verbose_name_plural': 'Цены работы за тираж',
                'ordering': ['work', 'circulation'],
                'indexes': [models.Index(fields=['work'], name='spravochnik_work_id_3ce352_idx'), models.Index(fields=['circulation'], name='spravochnik_circula_356b40_idx')],
                'unique_together': {('work', 'circulation')},
            },
        ),
    ]
