# Generated by Django 4.2.7 on 2026-03-22 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0009_alter_work_formula_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Себестоимость работы (без наценки)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость (руб)'),
        ),
        migrations.AddField(
            model_name='work',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент наценки от себестоимости (например, 20.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка (%)'),
        ),
        migrations.AlterField(
            model_name='work',
            name='k_lines',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Коэффициент, усиливающий влияние количества резов в формуле 4', max_digits=5, verbose_name='Коэффициент резов'),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Итоговая цена = себестоимость + наценка (рассчитывается автоматически)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='workcirculationprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Итоговая цена работы при данном тираже (включая наценку)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='workprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Итоговая цена работы при данном количестве листов (включая наценку)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб.)'),
        ),
    ]
