# Generated by Django 4.2.7 on 2026-09-24 22:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_alter_printer_devices_interpolation_method_laminator'),
        ('sklad', '0010_alter_material_markup_percent'),
        ('spravochnik_dopolnitelnyh_rabot', '0010_work_cost_work_markup_percent_alter_work_k_lines_and_more'),
        ('vichisliniya_listov', '0012_multipagebinding_default_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Простые визитки", "Листовки А5", "Брошюры А4 на скрепку"', max_length=200, verbose_name='Название калькулятора')),
                ('slug', models.SlugField(help_text='Латинскими буквами, без пробелов. Используется в URL: /web-calc/<slug>/', max_length=100, unique=True, verbose_name='Идентификатор (slug)')),
                ('product_type', models.CharField(choices=[('single', 'Одностраничное изделие'), ('multipage', 'Многостраничное изделие (брошюра)')], default='single', max_length=20, verbose_name='Тип изделия')),
                ('min_circulation', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальный тираж')),
                ('max_circulation', models.PositiveIntegerField(default=5000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный тираж')),
                ('is_active', models.BooleanField(default=True, help_text='Если снять галочку — калькулятор перестанет отвечать на API-запросы', verbose_name='Активен')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше калькулятор в списке', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Веб-калькулятор',
                'verbose_name_plural': 'Веб-калькуляторы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebCalculatorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной', help_text='Например: "Обложка", "Внутренний блок", "Основной"', max_length=100, verbose_name='Название компонента')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('allow_color_single', models.BooleanField(default=False, verbose_name='Цветная односторонняя')),
                ('allow_color_duplex', models.BooleanField(default=False, verbose_name='Цветная двусторонняя')),
                ('allow_bw_single', models.BooleanField(default=False, verbose_name='Ч/б односторонняя')),
                ('allow_bw_duplex', models.BooleanField(default=False, verbose_name='Ч/б двусторонняя')),
                ('lamination_enabled', models.BooleanField(default=False, verbose_name='Ламинация разрешена')),
                ('allow_lamination_single', models.BooleanField(default=False, verbose_name='Ламинация односторонняя')),
                ('allow_lamination_duplex', models.BooleanField(default=False, verbose_name='Ламинация двусторонняя')),
                ('min_width_mm', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=6, verbose_name='Мин. ширина (мм)')),
                ('max_width_mm', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=6, verbose_name='Макс. ширина (мм)')),
                ('min_height_mm', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=6, verbose_name='Мин. высота (мм)')),
                ('max_height_mm', models.DecimalField(decimal_places=2, default=Decimal('120.00'), max_digits=6, verbose_name='Макс. высота (мм)')),
                ('allow_booklet_portrait', models.BooleanField(default=True, verbose_name='Ориентация портретная разрешена')),
                ('allow_booklet_landscape', models.BooleanField(default=False, verbose_name='Ориентация альбомная разрешена')),
                ('min_pages', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Мин. страниц')),
                ('max_pages', models.PositiveIntegerField(default=64, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. страниц')),
                ('allowed_films', models.ManyToManyField(blank=True, help_text='Материалы из склада с типом "плёнка", которые клиент может выбрать', limit_choices_to={'type': 'film'}, related_name='web_calculator_components_as_film', to='sklad.material', verbose_name='Доступные плёнки')),
                ('allowed_papers', models.ManyToManyField(blank=True, help_text='Материалы из склада с типом "бумага", которые клиент может выбрать', limit_choices_to={'type': 'paper'}, related_name='web_calculator_components_as_paper', to='sklad.material', verbose_name='Доступные бумаги')),
                ('allowed_works', models.ManyToManyField(blank=True, help_text='Работы из справочника, которые клиент может добавить', related_name='web_calculator_components', to='spravochnik_dopolnitelnyh_rabot.work', verbose_name='Доступные работы')),
                ('binding', models.ForeignKey(blank=True, help_text='Только для многостраничных изделий. Заполняется у компонента-обложки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_calculator_components', to='vichisliniya_listov.multipagebinding', verbose_name='Способ скрепления')),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='web_calculators.webcalculator', verbose_name='Калькулятор')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='web_calculator_components', to='devices.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Компонент веб-калькулятора',
                'verbose_name_plural': 'Компоненты веб-калькулятора',
                'ordering': ['calculator', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebCalculatorSizePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина (мм)')),
                ('height_mm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Высота (мм)')),
                ('label', models.CharField(blank=True, default='', help_text='Например: "90×50". Если оставить пусто — сформируется автоматически.', max_length=50, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_presets', to='web_calculators.webcalculatorcomponent', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Пресет размера',
                'verbose_name_plural': 'Пресеты размеров',
                'ordering': ['component', 'order', 'width_mm', 'height_mm'],
            },
        ),
    ]
