# Generated by Django 4.2.7 on 2026-09-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_printer_devices_interpolation_method_laminator'),
        ('web_calculators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculatorcomponent',
            name='laminator',
            field=models.ForeignKey(blank=True, help_text='Заполняется только если ламинация разрешена', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='web_calculator_components', to='devices.laminator', verbose_name='Ламинатор'),
        ),
    ]
