# Generated by Django 4.2.7 on 2026-09-28 20:16
# Отредактировано вручную: порядок операций изменён на безопасный
# (сначала CreateModel, потом перенос данных, потом RemoveField).

from django.db import migrations, models
import django.db.models.deletion


def copy_allowed_works_forward(apps, schema_editor):
    """
    Переносит данные из старого M2M-поля allowed_works в новую модель
    WebCalculatorComponentWork.

    Все перенесённые работы помечаются как опциональные (is_always_on=False) —
    позже через админку вы сами решите, какие отметить как «всегда включённые».

    Важно: эта функция вызывается, когда в состоянии миграции
    ещё существует поле allowed_works (RemoveField идёт после RunPython),
    поэтому обращаться к нему безопасно.
    """
    WebCalculatorComponent = apps.get_model('web_calculators', 'WebCalculatorComponent')
    WebCalculatorComponentWork = apps.get_model('web_calculators', 'WebCalculatorComponentWork')

    # Перебираем все компоненты. У каждого — список связанных работ.
    for comp in WebCalculatorComponent.objects.all():
        order = 0
        # Через M2M: comp.allowed_works.all() — работает, потому что поле
        # ещё в state миграции.
        for work in comp.allowed_works.all():
            WebCalculatorComponentWork.objects.create(
                component_id=comp.id,
                work_id=work.id,
                is_always_on=False,
                order=order,
            )
            order += 1


def copy_allowed_works_backward(apps, schema_editor):
    """
    Обратная операция — на случай отката миграции.
    Данные в старой M2M-таблице не трогаем, просто ничего не делаем.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0010_work_cost_work_markup_percent_alter_work_k_lines_and_more'),
        ('web_calculators', '0002_webcalculatorcomponent_laminator'),
    ]

    operations = [
        # ===== 1. Создаём новую таблицу =====
        migrations.CreateModel(
            name='WebCalculatorComponentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_always_on', models.BooleanField(default=False, help_text='Если включено — работа не показывается галочкой в калькуляторе, но всегда прибавляется к стоимости', verbose_name='Всегда включена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('component', models.ForeignKey(help_text='Компонент, к которому относится работа', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='web_calculators.webcalculatorcomponent', verbose_name='Компонент')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_calculator_works', to='spravochnik_dopolnitelnyh_rabot.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Работа веб-калькулятора',
                'verbose_name_plural': 'Работы веб-калькулятора',
                'ordering': ['component', 'order', 'id'],
                'unique_together': {('component', 'work')},
            },
        ),
        # ===== 2. Переносим данные из старого M2M в новую таблицу =====
        migrations.RunPython(copy_allowed_works_forward, copy_allowed_works_backward),
        # ===== 3. Удаляем старое M2M-поле =====
        migrations.RemoveField(
            model_name='webcalculatorcomponent',
            name='allowed_works',
        ),
    ]