# Generated by Django 4.2.7 on 2026-09-28 20:43
# Отредактировано вручную: правильный порядок операций
# (сначала AddField, потом RunPython-перенос, потом RemoveField).

from django.db import migrations, models


def copy_is_always_on_to_trigger(apps, schema_editor):
    """
    Переносит данные из старого булева поля is_always_on в новое поле trigger.

    Логика:
    - Было True  → стало 'always'    (всегда включена).
    - Было False → стало 'optional'  (опциональная, по умолчанию).

    Триггер 'lamination' появится только когда пользователь сам выберет
    его в админке — при переносе мы не знаем, какие работы должны
    срабатывать при ламинации.
    """
    WebCalculatorComponentWork = apps.get_model('web_calculators', 'WebCalculatorComponentWork')

    # True → always
    WebCalculatorComponentWork.objects.filter(is_always_on=True).update(trigger='always')

    # False → optional (это default, но на всякий случай явно).
    WebCalculatorComponentWork.objects.filter(is_always_on=False).update(trigger='optional')


def copy_trigger_to_is_always_on(apps, schema_editor):
    """
    Обратная операция — на случай отката миграции.
    'always' → True, всё остальное → False.
    """
    WebCalculatorComponentWork = apps.get_model('web_calculators', 'WebCalculatorComponentWork')
    WebCalculatorComponentWork.objects.filter(trigger='always').update(is_always_on=True)
    WebCalculatorComponentWork.objects.exclude(trigger='always').update(is_always_on=False)


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculators', '0003_replace_allowed_works_with_component_work'),
    ]

    operations = [
        # ===== 1. Сначала ДОБАВЛЯЕМ новое поле trigger =====
        migrations.AddField(
            model_name='webcalculatorcomponentwork',
            name='trigger',
            field=models.CharField(
                choices=[
                    ('optional', 'Опционально (галочка в калькуляторе)'),
                    ('always', 'Всегда включена'),
                    ('lamination', 'При ламинации'),
                ],
                default='optional',
                help_text='Когда работа участвует в расчёте',
                max_length=20,
                verbose_name='Условие',
            ),
        ),
        # ===== 2. Переносим данные из старого поля в новое =====
        migrations.RunPython(copy_is_always_on_to_trigger, copy_trigger_to_is_always_on),
        # ===== 3. И только теперь УДАЛЯЕМ старое поле =====
        migrations.RemoveField(
            model_name='webcalculatorcomponentwork',
            name='is_always_on',
        ),
    ]