# Generated by Django 4.2.7 on 2026-09-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculators', '0004_replace_is_always_on_with_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculatorcomponentwork',
            name='preview_effect',
            field=models.CharField(choices=[('none', 'Без эффекта'), ('rounded_corners', 'Скруглённые углы')], default='none', help_text='Визуальный эффект, отображаемый на схеме в калькуляторе', max_length=30, verbose_name='Эффект в превью'),
        ),
    ]
