# Generated by Django 4.2.7 on 2026-09-28 21:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculators', '0005_add_preview_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='circulation_step',
            field=models.PositiveIntegerField(default=50, help_text='Тираж округляется до ближайшего кратного этому шагу', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Шаг тиража'),
        ),
        migrations.CreateModel(
            name='WebCalculatorCirculationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тираж (шт.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulation_presets', to='web_calculators.webcalculator', verbose_name='Калькулятор')),
            ],
            options={
                'verbose_name': 'Пресет тиража',
                'verbose_name_plural': 'Пресеты тиража',
                'ordering': ['calculator', 'order', 'value'],
                'unique_together': {('calculator', 'value')},
            },
        ),
    ]
