# Generated by Django 4.2.7 on 2026-09-28 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculators', '0006_add_circulation_step_and_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='default_circulation',
            field=models.PositiveIntegerField(default=100, help_text='Значение, которое клиент увидит в калькуляторе при открытии', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тираж по умолчанию'),
        ),
    ]
