# Generated by Django 4.2.7 on 2026-09-30 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculators', '0007_add_default_circulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculatorcomponent',
            name='vyleta_mm',
            field=models.PositiveIntegerField(default=4, help_text='Расстояние между соседними изделиями на листе. По умолчанию 4 мм.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Зазор между изделиями (мм)'),
        ),
    ]
