# Generated by Django 4.2.7 on 2026-09-30 20:14
# Отредактировано вручную: правильный порядок операций
# (сначала CreateModel, потом RunPython-перенос, потом RemoveField).

from django.db import migrations, models
import django.db.models.deletion


def copy_papers_forward(apps, schema_editor):
    """
    Переносит связи бумаг из старого M2M-поля allowed_papers
    в новую модель WebCalculatorComponentPaper.

    customer_name оставляем пустым — админ потом заполнит вручную.
    """
    WebCalculatorComponent = apps.get_model('web_calculators', 'WebCalculatorComponent')
    WebCalculatorComponentPaper = apps.get_model('web_calculators', 'WebCalculatorComponentPaper')

    for comp in WebCalculatorComponent.objects.all():
        order = 0
        # comp.allowed_papers.all() — работает, потому что поле ещё живо в state миграции.
        for material in comp.allowed_papers.all():
            WebCalculatorComponentPaper.objects.create(
                component_id=comp.id,
                material_id=material.id,
                customer_name='',
                order=order,
            )
            order += 1


def copy_films_forward(apps, schema_editor):
    """
    Переносит связи плёнок из старого M2M-поля allowed_films
    в новую модель WebCalculatorComponentFilm.
    """
    WebCalculatorComponent = apps.get_model('web_calculators', 'WebCalculatorComponent')
    WebCalculatorComponentFilm = apps.get_model('web_calculators', 'WebCalculatorComponentFilm')

    for comp in WebCalculatorComponent.objects.all():
        order = 0
        for material in comp.allowed_films.all():
            WebCalculatorComponentFilm.objects.create(
                component_id=comp.id,
                material_id=material.id,
                customer_name='',
                order=order,
            )
            order += 1


def copy_backward(apps, schema_editor):
    """
    Обратная операция — не делаем ничего. При откате старые M2M-поля
    восстановятся, но данные из них потеряются (это нормально для
    обратного отката — восстановление из бэкапа).
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0010_alter_material_markup_percent'),
        ('web_calculators', '0008_add_vyleta_mm'),
    ]

    operations = [
        # ===== 1. Сначала создаём новые таблицы =====
        migrations.CreateModel(
            name='WebCalculatorComponentPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', help_text='Если оставить пустым — клиент увидит полное складское название', max_length=200, verbose_name='Название для клиента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('component', models.ForeignKey(help_text='Компонент, к которому относится бумага', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='web_calculators.webcalculatorcomponent', verbose_name='Компонент')),
                ('material', models.ForeignKey(limit_choices_to={'type': 'paper'}, on_delete=django.db.models.deletion.CASCADE, related_name='web_calculator_papers', to='sklad.material', verbose_name='Бумага (со склада)')),
            ],
            options={
                'verbose_name': 'Доступная бумага',
                'verbose_name_plural': 'Доступные бумаги',
                'ordering': ['component', 'order', 'id'],
                'unique_together': {('component', 'material')},
            },
        ),
        migrations.CreateModel(
            name='WebCalculatorComponentFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', help_text='Если оставить пустым — клиент увидит полное складское название', max_length=200, verbose_name='Название для клиента')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('component', models.ForeignKey(help_text='Компонент, к которому относится плёнка', on_delete=django.db.models.deletion.CASCADE, related_name='films', to='web_calculators.webcalculatorcomponent', verbose_name='Компонент')),
                ('material', models.ForeignKey(limit_choices_to={'type': 'film'}, on_delete=django.db.models.deletion.CASCADE, related_name='web_calculator_films', to='sklad.material', verbose_name='Плёнка (со склада)')),
            ],
            options={
                'verbose_name': 'Доступная плёнка',
                'verbose_name_plural': 'Доступные плёнки',
                'ordering': ['component', 'order', 'id'],
                'unique_together': {('component', 'material')},
            },
        ),
        # ===== 2. Переносим данные из старых M2M в новые таблицы =====
        migrations.RunPython(copy_papers_forward, copy_backward),
        migrations.RunPython(copy_films_forward, copy_backward),
        # ===== 3. И только теперь удаляем старые M2M-поля =====
        migrations.RemoveField(
            model_name='webcalculatorcomponent',
            name='allowed_films',
        ),
        migrations.RemoveField(
            model_name='webcalculatorcomponent',
            name='allowed_papers',
        ),
    ]