# Generated by Django 4.2.7 on 2026-10-07 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculators', '0009_replace_m2m_with_through_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculatorcomponentwork',
            name='show_quantity',
            field=models.BooleanField(default=False, help_text='Показывать в калькуляторе поле выбора количества для этой работы. Стоимость работы умножается на выбранное количество.', verbose_name='Отображать количество'),
        ),
        migrations.CreateModel(
            name='WebCalculatorQuantityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество (шт.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_presets', to='web_calculators.webcalculator', verbose_name='Калькулятор')),
            ],
            options={
                'verbose_name': 'Пресет количества',
                'verbose_name_plural': 'Пресеты количества',
                'ordering': ['calculator', 'order', 'value'],
                'unique_together': {('calculator', 'value')},
            },
        ),
    ]
