# Generated by Django 4.2.7 on 2025-12-27 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название бумаги (например, "Мелованная 130г/м2, глянец")', max_length=100, unique=True, verbose_name='Название бумаги')),
                ('price_per_sheet', models.DecimalField(decimal_places=2, help_text='Введите цену за один лист бумаги в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена за лист (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бумага',
                'verbose_name_plural': 'Бумаги',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sklad_paper_name_df9d72_idx'), models.Index(fields=['price_per_sheet'], name='sklad_paper_price_p_c32e3b_idx')],
            },
        ),
    ]
