# Generated by Django 4.2.7 on 2025-12-27 20:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории (например: "Бумага", "Меловка")', max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории (необязательно)', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Выберите родительскую категорию (оставьте пустым для корневой)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sklad.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название материала (например: "Меловка 130 г/кв.м, глянец")', max_length=100, verbose_name='Название материала')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену за единицу материала', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена')),
                ('unit', models.CharField(default='лист', help_text='Введите единицу измерения (например: "лист", "рулон", "метр")', max_length=20, verbose_name='Единица измерения')),
                ('density', models.IntegerField(blank=True, help_text='Введите плотность материала в г/кв.м (только для бумаги)', null=True, verbose_name='Плотность (г/кв.м)')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Введите количество материала на складе', max_digits=10, verbose_name='Количество на складе')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=10, help_text='Минимальное количество, при котором нужно заказывать', max_digits=10, verbose_name='Минимальный остаток')),
                ('characteristics', models.JSONField(blank=True, default=dict, help_text='Дополнительные характеристики материала в формате JSON', null=True, verbose_name='Характеристики')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания о материале', null=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если материал активен и доступен для использования', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(help_text='Выберите категорию для материала', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='sklad.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='sklad_mater_name_f1843a_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['price'], name='sklad_mater_price_2c63d9_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active'], name='sklad_mater_is_acti_02e589_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='sklad_categ_name_182e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='sklad_category_tree_id_lft_idx'),
        ),
    ]
