# Generated by Django 4.2.7 on 2025-12-28 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_category_material_delete_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.IntegerField(default=10, help_text='Минимальное целое количество, при котором нужно заказывать', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Введите целое количество материала на складе', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе'),
        ),
    ]
