# Generated by Django 4.2.7 on 2026-02-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_alter_material_min_quantity_alter_material_quantity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='sklad_category_tree_id_lft_idx',
        ),
    ]
