# Generated by Django 4.2.7 on 2026-03-26 21:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0004_remove_category_sklad_category_tree_id_lft_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('paper', 'Бумага'), ('film', 'Плёнка')], default='paper', help_text='Выберите тип категории: Бумага или Плёнка', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='material',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Закупочная стоимость единицы', max_digits=10, null=True, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='material',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент наценки (от себестоимости)', max_digits=5, null=True, verbose_name='Наценка (%)'),
        ),
        migrations.AddField(
            model_name='material',
            name='thickness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Толщина плёнки в микронах', null=True, verbose_name='Толщина (мкм)'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('paper', 'Бумага'), ('film', 'Плёнка')], default='paper', help_text='Выберите тип материала: Бумага или Плёнка', max_length=20, verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='sklad.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='material',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плотность (г/кв.м)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_quantity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный остаток'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='лист', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type'], name='sklad_categ_type_84438d_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['type'], name='sklad_mater_type_79f49c_idx'),
        ),
    ]
