# Generated by Django 4.2.7 on 2026-03-29 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0005_category_type_material_cost_material_markup_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='paper_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Толщина бумаги в миллиметрах (например, 0.1 для 100 мкм)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Толщина бумаги (мм)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.IntegerField(blank=True, help_text='Плотность бумаги в граммах на квадратный метр', null=True, verbose_name='Плотность (г/кв.м)'),
        ),
    ]
