# Generated by Django 4.2.7 on 2026-04-04 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0006_material_paper_thickness_alter_material_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Закупочная стоимость единицы', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='material',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент наценки (от себестоимости)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка (%)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='thickness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Толщина плёнки в микронах', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Толщина (мкм)'),
        ),
    ]
