# Generated by Django 4.2.7 on 2026-04-04 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0007_alter_material_cost_alter_material_markup_percent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='sklad_mater_price_2c63d9_idx',
        ),
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Закупочная стоимость единицы материала', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость (руб.)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.IntegerField(blank=True, help_text='Плотность бумаги в граммах на квадратный метр (только для бумаги)', null=True, verbose_name='Плотность (г/кв.м)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, help_text='Процент наценки от себестоимости', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка (%)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='paper_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Толщина бумаги в миллиметрах (только для бумаги)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Толщина бумаги (мм)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='thickness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Толщина плёнки в микронах (только для плёнки)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Толщина (мкм)'),
        ),
    ]
