# Generated by Django 4.2.7 on 2026-04-04 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0008_remove_material_sklad_mater_price_2c63d9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Закупочная стоимость единицы материала', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость (руб.)'),
        ),
    ]
