# Generated by Django 4.2.7 on 2026-04-04 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0009_alter_material_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент наценки от себестоимости', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка (%)'),
        ),
    ]
