# Generated by Django 4.2.7 on 2025-12-22 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название формата (например, "SRA3", "A4", "A3+")', max_length=50, unique=True, verbose_name='Наименование формата')),
                ('width_mm', models.IntegerField(help_text='Введите ширину листа в миллиметрах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ширина (мм)')),
                ('height_mm', models.IntegerField(help_text='Введите высоту листа в миллиметрах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Высота (мм)')),
            ],
            options={
                'verbose_name': 'Формат печатного листа',
                'verbose_name_plural': 'Форматы печатных листов',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sheet_forma_name_bff176_idx')],
            },
        ),
    ]
