# Generated by Django 4.2.7 on 2025-12-28 21:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveIntegerField(default=1, help_text='Введите количество экземпляров для печати', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Количество копий')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Стоимость печати указанного тиража', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Стоимость печати (руб.)')),
                ('is_duplex', models.BooleanField(default=False, help_text='Отметьте, если нужна печать с двух сторон', verbose_name='Двусторонняя печать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания расчета')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('printer', models.ForeignKey(help_text='Выберите принтер для расчета стоимости', on_delete=django.db.models.deletion.CASCADE, related_name='print_prices', to='devices.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Расчет стоимости печати',
                'verbose_name_plural': 'Расчеты стоимости печати',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['printer'], name='print_price_printer_48e8f7_idx'), models.Index(fields=['copies'], name='print_price_copies_14de10_idx'), models.Index(fields=['created_at'], name='print_price_created_90ba56_idx')],
                'unique_together': {('printer', 'copies', 'is_duplex')},
            },
        ),
    ]
