# Generated by Django 4.2.7 on 2025-12-28 21:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('print_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printprice',
            options={'ordering': ['printer', 'copies'], 'verbose_name': 'Цена печати', 'verbose_name_plural': 'Цены печати'},
        ),
        migrations.RemoveIndex(
            model_name='printprice',
            name='print_price_created_90ba56_idx',
        ),
        migrations.AlterUniqueTogether(
            name='printprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='printprice',
            name='copies',
            field=models.PositiveIntegerField(default=1, help_text='Введите количество экземпляров для печати', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тираж (количество копий)'),
        ),
        migrations.AlterField(
            model_name='printprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='printprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Введите цену печати указанного тиража', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за тираж (руб.)'),
        ),
        migrations.AlterField(
            model_name='printprice',
            name='printer',
            field=models.ForeignKey(help_text='Выберите принтер для которого устанавливается цена', on_delete=django.db.models.deletion.CASCADE, related_name='print_prices', to='devices.printer', verbose_name='Принтер'),
        ),
        migrations.AlterUniqueTogether(
            name='printprice',
            unique_together={('printer', 'copies')},
        ),
        migrations.RemoveField(
            model_name='printprice',
            name='is_duplex',
        ),
    ]
