# Generated by Django 4.2.7 on 2025-12-28 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_price', '0002_alter_printprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printprice',
            options={'ordering': ['printer', 'copies'], 'verbose_name': 'Цена печати за лист', 'verbose_name_plural': 'Цены печати за лист'},
        ),
        migrations.RemoveField(
            model_name='printprice',
            name='price',
        ),
        migrations.AddField(
            model_name='printprice',
            name='price_per_sheet',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Введите цену печати одного листа при указанном тираже', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за 1 лист (руб.)'),
        ),
    ]
