# Generated by Django 4.2.7 on 2026-03-25 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_printer_devices_interpolation_method_and_more'),
        ('print_price', '0003_alter_printprice_options_remove_printprice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printprice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Себестоимость печати одного листа при данном тираже (без наценки)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость (руб.)'),
        ),
        migrations.AddField(
            model_name='printprice',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент наценки от себестоимости (например, 20.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка (%)'),
        ),
        migrations.AlterField(
            model_name='printprice',
            name='price_per_sheet',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Итоговая цена печати одного листа = себестоимость + наценка', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за 1 лист (руб.)'),
        ),
        migrations.AlterField(
            model_name='printprice',
            name='printer',
            field=models.ForeignKey(help_text='Выберите принтер, для которого устанавливается цена', on_delete=django.db.models.deletion.CASCADE, related_name='print_prices', to='devices.printer', verbose_name='Принтер'),
        ),
    ]
