# Generated by Django 4.2.7 on 2026-03-30 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_printer_devices_interpolation_method_laminator'),
        ('print_price', '0004_printprice_cost_printprice_markup_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printprice',
            options={'ordering': ['printer', 'copies'], 'verbose_name': 'Цена печати за лист (принтер)', 'verbose_name_plural': 'Цены печати за лист (принтеры)'},
        ),
        migrations.CreateModel(
            name='LaminatorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveIntegerField(default=1, help_text='Введите количество экземпляров для ламинирования', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тираж (количество копий)')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Себестоимость ламинирования одного листа при данном тираже (без наценки)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Себестоимость (руб.)')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Процент наценки от себестоимости', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наценка (%)')),
                ('price_per_sheet', models.DecimalField(decimal_places=2, default=0.0, help_text='Итоговая цена ламинирования одного листа = себестоимость + наценка', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за 1 лист (руб.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('laminator', models.ForeignKey(help_text='Выберите ламинатор, для которого устанавливается цена', on_delete=django.db.models.deletion.CASCADE, related_name='laminator_prices', to='devices.laminator', verbose_name='Ламинатор')),
            ],
            options={
                'verbose_name': 'Цена ламинирования за лист (ламинатор)',
                'verbose_name_plural': 'Цены ламинирования за лист (ламинаторы)',
                'ordering': ['laminator', 'copies'],
                'indexes': [models.Index(fields=['laminator'], name='print_price_laminat_434ebf_idx'), models.Index(fields=['copies'], name='print_price_copies_b2987b_idx')],
                'unique_together': {('laminator', 'copies')},
            },
        ),
    ]
