# Generated by Django 4.2.7 on 2026-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_printer_devices_interpolation_method_laminator'),
        ('print_price', '0005_alter_printprice_options_laminatorprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printprice',
            options={'ordering': ['printer', 'print_type', 'copies'], 'verbose_name': 'Цена печати за лист (принтер)', 'verbose_name_plural': 'Цены печати за лист (принтеры)'},
        ),
        migrations.AlterUniqueTogether(
            name='printprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='printprice',
            name='print_type',
            field=models.CharField(choices=[('color', 'Цветная печать'), ('bw', 'Чёрно-белая печать')], default='color', help_text='Выберите тип печати: цветная или чёрно-белая', max_length=10, verbose_name='Тип печати'),
        ),
        migrations.AlterUniqueTogether(
            name='printprice',
            unique_together={('printer', 'copies', 'print_type')},
        ),
        migrations.AddIndex(
            model_name='printprice',
            index=models.Index(fields=['print_type'], name='print_price_print_t_a6b457_idx'),
        ),
    ]
