"""
Django settings for clickcounter project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4kej=1toi&@-lykpnan(d7%yctg0posv6312a60k2a0v%lr&5v'

# ===== ЛОКАЛЬНАЯ РАЗРАБОТКА - ИЗМЕНИТЕ НА False ДЛЯ PRODUCTION! =====
DEBUG = True

# Для локальной разработки разрешаем всем
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'daphne',                    # ASGI-сервер для WebSocket
    'django.contrib.admin',      # Административная панель Django
    'django.contrib.auth',       # Система аутентификации и авторизации
    'django.contrib.contenttypes', # Система типов контента
    'django.contrib.sessions',   # Механизм сессий
    'django.contrib.messages',   # Система сообщений
    'django.contrib.staticfiles', # Обработка статических файлов (CSS, JS, изображения)
    'channels',                  # Поддержка WebSocket и асинхронных запросов
    'counter',                   # Приложение "Список заказов" (управление заказами)
    'calculator',                # Приложение "Калькулятор заказов"
    'product_templates',         # Приложение "Шаблоны изделий" (создали ранее)
    'directories',               # НОВОЕ ПРИЛОЖЕНИЕ: "Справочники" (базы данных оборудования, материалов и т.д.)
    'devices',
]
# Важно: порядок приложений имеет значение!
# Приложения, от которых зависят другие, должны быть выше в списке.
# Наше новое приложение directories может зависеть от counter (аутентификация),
# поэтому размещаем его после counter.



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clickcounter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clickcounter.wsgi.application'
ASGI_APPLICATION = 'clickcounter.asgi.application'

# ===== CHANNEL LAYERS - ДЛЯ ЛОКАЛЬНОЙ РАЗРАБОТКИ =====
# Используем InMemory (не требует Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# Для production используйте Redis:
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# ===== БАЗА ДАННЫХ - ОТНОСИТЕЛЬНЫЙ ПУТЬ ДЛЯ ЛОКАЛЬНОЙ РАЗРАБОТКИ =====
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# ===== СТАТИЧЕСКИЕ ФАЙЛЫ - ОТНОСИТЕЛЬНЫЙ ПУТЬ =====
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Для локальной разработки не используем WhiteNoise
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ===== МЕДИА ФАЙЛЫ =====
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== ДЛЯ ЛОКАЛЬНОЙ РАЗРАБОТКИ - ОТКЛЮЧАЕМ SSL/HTTPS =====
# Для production включите эти строки:
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# ===== ЛОГИРОВАНИЕ - РАБОТАЕТ НА ВСЕХ ОС =====
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# ===== НАСТРОЙКИ АУТЕНТИФИКАЦИИ =====
# URL для перенаправления при необходимости входа
LOGIN_URL = '/counter/login/'  # Изменяем с '/login/' на '/counter/login/'

# URL для перенаправления после успешного входа
LOGIN_REDIRECT_URL = '/'  # Оставляем как есть (будет перенаправлять на /counter/)

# URL для перенаправления после выхода
LOGOUT_REDIRECT_URL = '/counter/login/'  # Изменяем с '/login/' на '/counter/login/'

# Время жизни сессии в секундах (30 дней)
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60

# Сохранять сессию при закрытии браузера
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Использовать сессии для хранения данных аутентификации
SESSION_SAVE_EVERY_REQUEST = True