# Generated by Django 4.2.7 on 2026-01-08 14:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_printer_devices_interpolation_method_and_more'),
        ('sklad', '0003_alter_material_min_quantity_alter_material_quantity'),
        ('baza_klientov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proschet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Автоматически генерируется в формате PR-1, PR-2 и т.д.', max_length=20, unique=True, verbose_name='Номер просчёта')),
                ('title', models.CharField(help_text='Краткое описание заказа', max_length=200, verbose_name='Название просчёта')),
                ('circulation', models.PositiveIntegerField(blank=True, default=1, help_text='Количество экземпляров продукции (тираж). Необязательное поле. По умолчанию: 1', null=True, verbose_name='Тираж')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания просчёта', verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, help_text='Помечает просчёт как удаленный', verbose_name='Удален')),
                ('client', models.ForeignKey(blank=True, help_text='Клиент, для которого выполняется просчёт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baza_klientov.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Просчёт',
                'verbose_name_plural': 'Просчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Автоматически генерируется в формате KP-1, KP-2 и т.д.', max_length=20, unique=True, verbose_name='Номер компонента')),
                ('sheet_count', models.PositiveIntegerField(blank=True, help_text='Количество печатных листов. Необязательное поле.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество листов')),
                ('price_per_sheet', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость печати одного листа в рублях (без учета стоимости материала). Рассчитывается автоматически на основе принтера и тиража.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена печати за лист')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления компонента', verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, help_text='Помечает компонент как удаленный', verbose_name='Удален')),
                ('is_price_calculated', models.BooleanField(default=False, help_text='Указывает, что цена за лист была рассчитана автоматически на основе справочника цен', verbose_name='Цена рассчитана автоматически')),
                ('paper', models.ForeignKey(blank=True, help_text='Выберите бумагу из списка материалов на складе. Необязательное поле.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.material', verbose_name='Бумага')),
                ('printer', models.ForeignKey(blank=True, help_text='Выберите принтер из списка доступных устройств', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_components', to='devices.printer', verbose_name='Принтер')),
                ('proschet', models.ForeignKey(help_text='Просчёт, к которому относится этот компонент', on_delete=django.db.models.deletion.CASCADE, related_name='print_components', to='calculator.proschet', verbose_name='Просчёт')),
            ],
            options={
                'verbose_name': 'Компонент печати',
                'verbose_name_plural': 'Компоненты печати',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Автоматически генерируется в формата DR-1, DR-2 и т.д.', max_length=20, unique=True, verbose_name='Номер работы')),
                ('title', models.CharField(help_text='Название дополнительной работы', max_length=200, verbose_name='Название работы')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость работы в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления работы', verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, help_text='Помечает работу как удаленную', verbose_name='Удален')),
                ('proschet', models.ForeignKey(help_text='Просчёт, к которому относится эта работа', on_delete=django.db.models.deletion.CASCADE, related_name='additional_works', to='calculator.proschet', verbose_name='Просчёт')),
            ],
            options={
                'verbose_name': 'Дополнительная работа',
                'verbose_name_plural': 'Дополнительные работы',
                'ordering': ['created_at'],
            },
        ),
    ]
