# Generated by Django 4.2.7 on 2026-01-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printcomponent',
            name='is_price_calculated',
        ),
        migrations.RemoveField(
            model_name='printcomponent',
            name='price_per_sheet',
        ),
    ]
