# Generated by Django 4.2.7 on 2026-01-08 15:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_printcomponent_is_price_calculated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcomponent',
            name='is_price_calculated',
            field=models.BooleanField(default=False, help_text='Указывает, что цена за лист была рассчитана автоматически на основе справочника цен', verbose_name='Цена рассчитана автоматически'),
        ),
        migrations.AddField(
            model_name='printcomponent',
            name='price_per_sheet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость печати одного листа в рублях (без учета стоимости материала). Рассчитывается АВТОМАТИЧЕСКИ на основе принтера и тиража.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена печати за лист'),
        ),
    ]
