# Generated by Django 4.2.7 on 2026-01-08 15:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_printcomponent_price_per_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printcomponent',
            name='price_per_sheet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость печати одного листа в рублях (без учета стоимости материала). Рассчитывается автоматически на основе принтера и тиража.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена печати за лист'),
        ),
    ]
