# Generated by Django 4.2.7 on 2026-01-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_printcomponent_price_per_sheet'),
    ]

    operations = [
    ]
