# Generated by Django 4.2.7 on 2026-01-08 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_alter_printcomponent_price_per_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printcomponent',
            name='sheet_count',
            field=models.PositiveIntegerField(blank=True, help_text='Количество печатных листов. Автоматически берется из тиража связанного просчёта.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество листов'),
        ),
    ]
