# Generated by Django 4.2.7 on 2026-01-08 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_alter_printcomponent_sheet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printcomponent',
            name='sheet_count',
            field=models.PositiveIntegerField(blank=True, help_text='Количество печатных листов. Необязательное поле.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество листов'),
        ),
    ]
