# Generated by Django 4.2.7 on 2026-01-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_alter_printcomponent_sheet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proschet',
            name='circulation',
            field=models.PositiveIntegerField(default=1, help_text='Количество экземпляров продукции (тираж). По умолчанию: 1', verbose_name='Тираж'),
        ),
    ]
