# Generated by Django 4.2.7 on 2026-01-30 22:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_alter_proschet_circulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printcomponent',
            name='price_per_sheet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость печати одного листа в рублях (без учета стоимости материала). Рассчитывается АВТОМАТИЧЕСКИ на основе принтера и количества листов.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена печати за лист'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='sheet_count',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Количество печатных листов. Получается из приложения "Вычисления листов" (vichisliniya_listov).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество листов'),
        ),
    ]
