# Generated by Django 4.2.7 on 2026-02-11 19:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_alter_material_min_quantity_alter_material_quantity'),
        ('calculator', '0015_alter_printcomponent_price_per_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='number',
            field=models.CharField(blank=True, help_text='Автоматически генерируется в формате DR-1, DR-2 и т.д.', max_length=20, unique=True, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='paper',
            field=models.ForeignKey(blank=True, help_text='Выберите бумагу из списка материалов на складе.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.material', verbose_name='Бумага'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='price_per_sheet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость печати одного листа в рублях (рассчитывается автоматически).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена печати за лист'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='sheet_count',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Количество печатных листов. Получается из приложения "Вычисления листов".', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество листов'),
        ),
    ]
