# Generated by Django 4.2.7 on 2026-02-23 21:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0016_alter_additionalwork_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcomponent',
            name='total_circulation_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Итоговая стоимость компонента = (цена печати + цена бумаги) × количество листов. Сохраняется автоматически.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость'),
        ),
    ]
