# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations, models
import django.db.models.deletion

def migrate_additional_works_to_components(apps, schema_editor):
    """
    Для каждой существующей дополнительной работы пытаемся найти первый печатный компонент
    в том же просчёте и привязать работу к нему.
    Если компонентов нет, работа остаётся с print_component = NULL (будет удалена позже или исправлена вручную).
    """
    AdditionalWork = apps.get_model('calculator', 'AdditionalWork')
    PrintComponent = apps.get_model('calculator', 'PrintComponent')

    works_migrated = 0
    works_skipped = 0

    for work in AdditionalWork.objects.all():
        # У работы есть поле proschet (старое) и новое поле print_component (пока пустое)
        if work.proschet_id:
            # Ищем первый активный компонент в этом просчёте
            component = PrintComponent.objects.filter(
                proschet_id=work.proschet_id,
                is_deleted=False
            ).first()
            if component:
                work.print_component = component
                work.save()
                works_migrated += 1
            else:
                # Если компонентов нет, оставляем print_component = None
                work.print_component = None
                work.save()
                works_skipped += 1
        else:
            # Если просчёт не указан (такого быть не должно, но на всякий случай)
            work.print_component = None
            work.save()
            works_skipped += 1

    print(f"Миграция дополнительных работ завершена. Привязано: {works_migrated}, пропущено (нет компонента): {works_skipped}")

def reverse_migration(apps, schema_editor):
    """
    Откат: переносим работы обратно в просчёт (если нужно восстановить старую структуру).
    Здесь мы просто сбрасываем print_component в NULL, так как поле proschet уже будет восстановлено.
    """
    AdditionalWork = apps.get_model('calculator', 'AdditionalWork')
    AdditionalWork.objects.all().update(print_component=None)

class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_printcomponent_total_circulation_price'),  # ⚠️ ЗАМЕНИТЕ НА АКТУАЛЬНУЮ ПРЕДЫДУЩУЮ МИГРАЦИЮ
    ]

    operations = [
        # 1. Добавляем поле print_component (сначала разрешаем NULL)
        migrations.AddField(
            model_name='additionalwork',
            name='print_component',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='additional_works',
                to='calculator.printcomponent',
                verbose_name='Печатный компонент'
            ),
        ),
        # 2. Переносим данные
        migrations.RunPython(migrate_additional_works_to_components, reverse_migration),
        # 3. Удаляем старое поле proschet
        migrations.RemoveField(
            model_name='additionalwork',
            name='proschet',
        ),
        # 4. Делаем поле print_component обязательным (после успешного переноса)
        migrations.AlterField(
            model_name='additionalwork',
            name='print_component',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='additional_works',
                to='calculator.printcomponent',
                verbose_name='Печатный компонент'
            ),
        ),
    ]

