# Generated by Django 4.2.7 on 2026-02-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0018_add_print_component_to_additionalwork'),
    ]

    operations = [
    ]
