# Generated by Django 4.2.7 on 2026-02-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0019_migrate_additional_works_to_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='print_component',
            field=models.ForeignKey(help_text='Печатный компонент, к которому относится эта дополнительная работа', on_delete=django.db.models.deletion.CASCADE, related_name='additional_works', to='calculator.printcomponent', verbose_name='Печатный компонент'),
        ),
    ]
