# Generated by Django 4.2.7 on 2026-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0021_add_missing_title_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='title',
            field=models.CharField(help_text='Название дополнительной работы', max_length=200, verbose_name='Название работы'),
        ),
    ]
