# Generated by Django 4.2.7 on 2026-03-01 17:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0023_add_price_field_manual'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='additionalwork',
                    name='quantity',
                    field=models.PositiveIntegerField(
                        default=1,
                        help_text='Количество единиц данной работы (по умолчанию 1)',
                        verbose_name='Количество'
                    ),
                ),
            ],
            database_operations=[],  # Поле уже есть в БД, поэтому ничего не делаем
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Стоимость работы в рублях',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Цена'
            ),
        ),
    ]