# Generated by Django A.B on YYYY-MM-DD HH:MM
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0024_additionalwork_quantity_alter_additionalwork_price'),  # предыдущая миграция
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='additionalwork',
                    name='total_price',
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Общая стоимость работы = цена × количество',
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Общая стоимость',
                    ),
                ),
            ],
            database_operations=[],  # ничего не делаем в БД, так как поле уже существует
        ),
    ]