# Generated by Django A.B on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0025_add_total_price_to_additionalwork'),
        ('spravochnik_dopolnitelnyh_rabot', '0001_initial'),  # укажите правильную зависимость для справочника
    ]

    operations = [
        # Снимаем ограничение NOT NULL с колонки work_id
        migrations.RunSQL(
            sql='ALTER TABLE calculator_additionalwork ALTER COLUMN work_id DROP NOT NULL;',
            reverse_sql='ALTER TABLE calculator_additionalwork ALTER COLUMN work_id SET NOT NULL;',
        ),
        # Добавляем поле в состояние Django (столбец уже существует в БД)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='additionalwork',
                    name='work',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='spravochnik_dopolnitelnyh_rabot.Work',
                        verbose_name='Работа из справочника',
                        help_text='Ссылка на запись в справочнике дополнительных работ'
                    ),
                ),
            ],
            database_operations=[],  # ничего не делаем, столбец уже существует
        ),
    ]