# Generated by Django 4.2.7 on 2026-03-01 21:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0026_add_work_fk_to_additionalwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalwork',
            name='formula_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена'), (3, 'Тираж × Цена × Количество линий реза'), (4, 'Количество листов × Цена × Количество линий реза'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, help_text='Тип формулы, используемой для расчёта общей стоимости.', verbose_name='Формула расчёта'),
        ),
        migrations.AddField(
            model_name='additionalwork',
            name='items_per_sheet',
            field=models.PositiveIntegerField(default=1, help_text='Количество изделий на листе (используется в формулах 5 и 6).', verbose_name='Количество изделий на листе'),
        ),
        migrations.AddField(
            model_name='additionalwork',
            name='lines_count',
            field=models.PositiveIntegerField(default=1, help_text='Количество линий реза (используется в формулах 3 и 4).', verbose_name='Количество линий реза'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общая стоимость работы = результат применения формулы', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость'),
        ),
    ]
