# Generated by Django 4.2.7 on 2026-03-08 20:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravochnik_dopolnitelnyh_rabot', '0003_work_interpolation_method_and_more'),
        ('calculator', '0027_additionalwork_formula_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Базовая стоимость работы в рублях (из справочника или введённая вручную)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общая стоимость работы = результат применения формулы, где используется effective_price (интерполированная цена)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='work',
            field=models.ForeignKey(blank=True, help_text='Ссылка на запись в справочнике дополнительных работ (если работа была добавлена из справочника)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='spravochnik_dopolnitelnyh_rabot.work', verbose_name='Работа из справочника'),
        ),
    ]
