# Generated by Django 4.2.7 on 2026-03-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0028_alter_additionalwork_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='formula_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена'), (3, 'Цена × Количество листов × (Количество резов × Коэффициент)'), (4, 'Количество листов × Цена × Количество резов (логарифмическая)'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, help_text='Тип формулы, используемой для расчёта общей стоимости.', verbose_name='Формула расчёта'),
        ),
    ]
