# Generated by Django 4.2.7 on 2026-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0029_alter_additionalwork_formula_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcomponent',
            name='color_mode',
            field=models.CharField(default='4+0', help_text='Формат цветности, например 4+0, 4+4 и т.п.', max_length=10, verbose_name='Цветность'),
        ),
    ]
