# Generated by Django 4.2.7 on 2026-03-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0029_add_work_field_if_not_exists'),
        ('calculator', '0029_alter_additionalwork_formula_type'),
    ]

    operations = [
    ]
