# Generated by Django 4.2.7 on 2026-03-10 21:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0031_fix_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalwork',
            name='formula_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена'), (3, 'Цена × Количество листов × (Количество резов × Коэффициент)'), (4, 'Количество листов × Цена × Количество резов (логарифмическая)'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, help_text='Тип формулы, используемой для расчёта общей стоимости.', verbose_name='Формула расчёта'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='items_per_sheet',
            field=models.PositiveIntegerField(default=1, help_text='Количество изделий на листе (используется в формулах 5 и 6).', verbose_name='Количество изделий на листе'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='lines_count',
            field=models.PositiveIntegerField(default=1, help_text='Количество линий реза (используется в формулах 3 и 4).', verbose_name='Количество линий реза'),
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общая стоимость работы = результат применения формулы, где используется effective_price (интерполированная цена)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость'),
        ),
    ]
