# Generated by Django 4.2.7 on 2026-03-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0031_drop_color_column'),
        ('calculator', '0032_alter_additionalwork_formula_type_and_more'),
    ]

    operations = [
    ]
