# Generated by Django 4.2.7 on 2026-03-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0033_alter_additionalwork_formula_type'),
        ('calculator', '0033_merge_20260314_1513'),
    ]

    operations = [
    ]
