# Generated by Django 4.2.7 on 2026-03-15 10:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0033_alter_additionalwork_formula_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcomponent',
            name='printing_mode',
            field=models.CharField(choices=[('single', 'Односторонняя'), ('duplex', 'Двусторонняя')], default='single', help_text='Односторонняя или двусторонняя печать. Влияет на количество прогонов принтера.', max_length=10, verbose_name='Режим печати'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='total_circulation_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Итоговая стоимость компонента = (цена печати за прогон * количество прогонов) + (цена бумаги * количество листов). Сохраняется автоматически.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость'),
        ),
    ]
