# Generated by Django 4.2.7 on 2026-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0034_printcomponent_printing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalwork',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Себестоимость работы (без наценки)', max_digits=10, verbose_name='Себестоимость (руб)'),
        ),
        migrations.AddField(
            model_name='additionalwork',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Процент наценки от себестоимости', max_digits=5, verbose_name='Наценка (%)'),
        ),
    ]
