# Generated by Django 4.2.7 on 2026-03-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0034_merge_20260315_0251'),
        ('calculator', '0034_printcomponent_printing_mode_and_more'),
    ]

    operations = [
    ]
