# Generated by Django 4.2.7 on 2026-03-30 21:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_printer_devices_interpolation_method_laminator'),
        ('sklad', '0006_material_paper_thickness_alter_material_density'),
        ('calculator', '0035_additionalwork_cost_additionalwork_markup_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Отметьте, если требуется ламинирование', verbose_name='Ламинация включена')),
                ('laminator_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Себестоимость работы ламинатора на один лист (интерполяция)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Себестоимость ламинации (руб./лист)')),
                ('laminator_markup', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Наценка ламинатора (процент от себестоимости)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Наценка ламинатора (%)')),
                ('laminator_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Итоговая цена работы ламинатора за один лист', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена ламинации (руб./лист)')),
                ('film_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена одного листа плёнки (из склада)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена плёнки (руб./лист)')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(цена ламинации + цена плёнки) × количество листов', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость ламинации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('film', models.ForeignKey(blank=True, help_text='Выберите плёнку из склада', limit_choices_to={'type': 'film'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.material', verbose_name='Плёнка')),
                ('laminator', models.ForeignKey(blank=True, help_text='Выберите ламинатор, на котором будет выполняться ламинация', null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.laminator', verbose_name='Ламинатор')),
                ('print_component', models.OneToOneField(help_text='Печатный компонент, к которому применяется ламинация', on_delete=django.db.models.deletion.CASCADE, related_name='lamination', to='calculator.printcomponent', verbose_name='Печатный компонент')),
            ],
            options={
                'verbose_name': 'Ламинация',
                'verbose_name_plural': 'Ламинации',
                'ordering': ['-created_at'],
            },
        ),
    ]
