# Generated by Django 4.2.7 on 2026-03-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0035_additionalwork_cost_additionalwork_markup_percent'),
        ('calculator', '0035_merge_20260315_1352'),
    ]

    operations = [
    ]
