# Generated by Django 4.2.7 on 2026-04-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0036_laminate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printcomponent',
            name='sheet_count',
        ),
    ]
