# Generated by Django 4.2.7 on 2026-04-04 22:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0037_remove_sheet_count_from_printcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminate',
            name='side',
            field=models.CharField(choices=[('single', 'Односторонняя'), ('duplex', 'Двусторонняя')], default='single', help_text='Односторонняя или двусторонняя ламинация. При двусторонней расход плёнки удваивается.', max_length=10, verbose_name='Сторона ламинации'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='(цена ламинации + цена плёнки × коэффициент стороны) × количество листов', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общая стоимость ламинации'),
        ),
    ]
