# Generated by Django 4.2.7 on 2026-04-05 15:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0038_laminate_side_alter_laminate_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcomponent',
            name='print_type',
            field=models.CharField(choices=[('color', 'Цветная'), ('bw', 'Ч/б')], default='color', help_text='Цветная или чёрно-белая печать. Влияет на справочник цен.', max_length=10, verbose_name='Тип печати'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='price_per_sheet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость печати одного листа в рублях (рассчитывается автоматически на основе типа печати).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена печати за лист'),
        ),
    ]
