# Generated by Django 4.2.7 on 2026-08-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0037_alter_additionalwork_formula_type'),
        ('calculator', '0039_printcomponent_print_type_and_more'),
    ]

    operations = [
    ]
