# Generated by Django 4.2.7 on 2026-09-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shablony_proschetov', '0001_initial'),
        ('calculator', '0042_add_color_mode_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='proschet',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон, из которого был создан этот просчёт (может быть пустым)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proschets', to='shablony_proschetov.proschettemplate', verbose_name='Исходный шаблон'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='color_mode',
            field=models.CharField(default='4+0', help_text='Формат цветности, например 4+0, 4+4 и т.п.', max_length=10, verbose_name='Цветность'),
        ),
        migrations.AlterField(
            model_name='printcomponent',
            name='print_type',
            field=models.CharField(choices=[('color', 'Цветная'), ('bw', 'Ч/б')], default='color', help_text='Цветная или чёрно-белая печать. Влияет на справочник цен.', max_length=10, verbose_name='Тип печати'),
        ),
    ]
