# Generated by Django 4.2.7 on 2026-01-05 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(editable=False, help_text='Уникальный номер клиента в формате K-XXX', max_length=20, unique=True, verbose_name='Номер клиента')),
                ('name', models.CharField(help_text='Полное наименование организации или ФИО физического лица', max_length=255, verbose_name='Название/ФИО')),
                ('address', models.TextField(blank=True, help_text='Юридический и фактический адрес', null=True, verbose_name='Адрес')),
                ('bank_details', models.TextField(blank=True, help_text='Расчетный счет, БИК, банк и другие реквизиты', null=True, verbose_name='Банковские реквизиты')),
                ('discount', models.PositiveIntegerField(default=0, help_text='Размер скидки в процентах (от 0 до 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)')),
                ('has_edo', models.BooleanField(default=False, help_text='Отметьте, если клиент работает через электронный документооборот', verbose_name='ЭДО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Полное имя контактного лица', max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, help_text='Должность контактного лица', max_length=255, null=True, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, help_text='Стационарный телефон с кодом города', max_length=50, null=True, verbose_name='Телефон')),
                ('mobile', models.CharField(blank=True, help_text='Мобильный телефон', max_length=50, null=True, verbose_name='Сотовый')),
                ('email', models.EmailField(blank=True, help_text='Адрес электронной почты', max_length=254, null=True, verbose_name='E-mail')),
                ('comments', models.TextField(blank=True, help_text='Дополнительная информация о контактном лице', null=True, verbose_name='Комментарии')),
                ('is_primary', models.BooleanField(default=False, help_text='Отметьте, если это основное контактное лицо', verbose_name='Основное контактное лицо')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='baza_klientov.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_number'], name='baza_klient_client__405d89_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='baza_klient_name_bc34f0_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='baza_klient_created_d83634_idx'),
        ),
        migrations.AddIndex(
            model_name='contactperson',
            index=models.Index(fields=['client', 'is_primary'], name='baza_klient_client__ef0fc2_idx'),
        ),
    ]
