# Generated by Django 4.2.7 on 2026-09-17 22:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_alter_printer_devices_interpolation_method_laminator'),
        ('spravochnik_dopolnitelnyh_rabot', '0010_work_cost_work_markup_percent_alter_work_k_lines_and_more'),
        ('calculator', '0042_add_color_mode_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vichisliniya_listov', '0011_alter_vichisliniyamultipagemodel_booklet_orientation_and_more'),
        ('sklad', '0010_alter_material_markup_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProschetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Визитки 90×50 односторонние цветные на меловке 350 г"', max_length=200, verbose_name='Название шаблона')),
                ('comment', models.TextField(blank=True, default='', help_text='Например, для каких клиентов используется шаблон', verbose_name='Комментарий')),
                ('circulation', models.PositiveIntegerField(default=100, help_text='Количество экземпляров, подставляемое по умолчанию', verbose_name='Типовой тираж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон просчёта',
                'verbose_name_plural': 'Шаблоны просчётов',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplatePrintComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше компонент в списке', verbose_name='Порядок')),
                ('print_type', models.CharField(choices=[('color', 'Цветная'), ('bw', 'Ч/б')], default='color', help_text='Цветная или чёрно-белая печать', max_length=10, verbose_name='Тип печати')),
                ('printing_mode', models.CharField(choices=[('single', 'Односторонняя'), ('duplex', 'Двусторонняя')], default='single', help_text='Односторонняя или двусторонняя печать', max_length=10, verbose_name='Режим печати')),
                ('paper', models.ForeignKey(blank=True, help_text='Бумага, выбранная для этого компонента', limit_choices_to={'type': 'paper'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_print_components', to='sklad.material', verbose_name='Бумага')),
                ('printer', models.ForeignKey(blank=True, help_text='Принтер, выбранный для этого компонента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_print_components', to='devices.printer', verbose_name='Принтер')),
                ('template', models.ForeignKey(help_text='Шаблон, к которому относится этот компонент', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='shablony_proschetov.proschettemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Компонент печати (шаблон)',
                'verbose_name_plural': 'Компоненты печати (шаблон)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVichisliniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vyleta', models.PositiveIntegerField(default=1, verbose_name='Зазор, мм')),
                ('color', models.CharField(choices=[('1+0', '1+0 (односторонняя одноцветная)'), ('1+1', '1+1 (двусторонняя одноцветная)'), ('4+0', '4+0 (односторонняя полноцветная)'), ('4+4', '4+4 (двусторонняя полноцветная)')], default='4+0', max_length=10, verbose_name='Цветность')),
                ('item_width', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=6, verbose_name='Ширина изделия, мм')),
                ('item_height', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=6, verbose_name='Высота изделия, мм')),
                ('fit_horizontal', models.PositiveIntegerField(default=0, verbose_name='По горизонтали')),
                ('fit_vertical', models.PositiveIntegerField(default=0, verbose_name='По вертикали')),
                ('fit_total', models.PositiveIntegerField(default=0, verbose_name='Всего на листе')),
                ('fit_landscape_total', models.PositiveIntegerField(default=0, verbose_name='Альбомная ориентация')),
                ('fit_portrait_total', models.PositiveIntegerField(default=0, verbose_name='Портретная ориентация')),
                ('fit_selected_orientation', models.CharField(choices=[('landscape', 'Альбомная'), ('portrait', 'Портретная'), ('auto', 'Авто (оптимальная)')], default='auto', max_length=10, verbose_name='Выбранная ориентация')),
                ('cuts_count', models.PositiveIntegerField(default=0, verbose_name='Количество резов')),
                ('template_component', models.OneToOneField(help_text='Компонент, к которому привязан одностраничный расчёт', on_delete=django.db.models.deletion.CASCADE, related_name='vichisliniya', to='shablony_proschetov.templateprintcomponent', verbose_name='Компонент шаблона')),
            ],
            options={
                'verbose_name': 'Вычисление листов (шаблон, одностраничное)',
                'verbose_name_plural': 'Вычисления листов (шаблон, одностраничное)',
            },
        ),
        migrations.CreateModel(
            name='TemplateMultipage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.PositiveIntegerField(default=4, verbose_name='Количество страниц')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='Количество экземпляров')),
                ('finished_width', models.DecimalField(decimal_places=2, default=Decimal('210.00'), max_digits=6, verbose_name='Ширина страницы, мм')),
                ('finished_height', models.DecimalField(decimal_places=2, default=Decimal('297.00'), max_digits=6, verbose_name='Высота страницы, мм')),
                ('vyleta', models.PositiveIntegerField(default=1, verbose_name='Зазор, мм')),
                ('color', models.CharField(choices=[('1+0', '1+0 (односторонняя одноцветная)'), ('1+1', '1+1 (двусторонняя одноцветная)'), ('4+0', '4+0 (односторонняя полноцветная)'), ('4+4', '4+4 (двусторонняя полноцветная)')], default='4+0', max_length=10, verbose_name='Цветность')),
                ('booklet_orientation', models.CharField(choices=[('portrait', 'Вертикальная (портретная)'), ('landscape', 'Горизонтальная (альбомная)')], default='portrait', max_length=10, verbose_name='Ориентация брошюры')),
                ('fit_horizontal', models.PositiveIntegerField(default=0, verbose_name='По горизонтали')),
                ('fit_vertical', models.PositiveIntegerField(default=0, verbose_name='По вертикали')),
                ('fit_total', models.PositiveIntegerField(default=0, verbose_name='Всего на одной стороне')),
                ('fit_landscape_total', models.PositiveIntegerField(default=0, verbose_name='Альбомная ориентация')),
                ('fit_portrait_total', models.PositiveIntegerField(default=0, verbose_name='Портретная ориентация')),
                ('fit_selected_orientation', models.CharField(choices=[('landscape', 'Альбомная'), ('portrait', 'Портретная'), ('auto', 'Авто (оптимальная)')], default='auto', max_length=10, verbose_name='Выбранная ориентация')),
                ('is_active', models.BooleanField(default=False, verbose_name='Многостраничный режим активен')),
                ('binding', models.ForeignKey(blank=True, help_text='Способ скрепления брошюры', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_multipages', to='vichisliniya_listov.multipagebinding', verbose_name='Способ скрепления')),
                ('template_component', models.OneToOneField(help_text='Компонент, к которому привязан многостраничный расчёт', on_delete=django.db.models.deletion.CASCADE, related_name='multipage', to='shablony_proschetov.templateprintcomponent', verbose_name='Компонент шаблона')),
            ],
            options={
                'verbose_name': 'Вычисление листов (шаблон, многостраничное)',
                'verbose_name_plural': 'Вычисления листов (шаблон, многостраничное)',
            },
        ),
        migrations.CreateModel(
            name='TemplateLaminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Ламинация включена')),
                ('side', models.CharField(choices=[('single', 'Односторонняя'), ('duplex', 'Двусторонняя')], default='single', max_length=10, verbose_name='Сторона ламинации')),
                ('film', models.ForeignKey(blank=True, help_text='Плёнка, выбранная для ламинации', limit_choices_to={'type': 'film'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_laminations', to='sklad.material', verbose_name='Плёнка')),
                ('laminator', models.ForeignKey(blank=True, help_text='Ламинатор, выбранный для этого компонента', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_laminations', to='devices.laminator', verbose_name='Ламинатор')),
                ('template_component', models.OneToOneField(help_text='Компонент, к которому привязана ламинация', on_delete=django.db.models.deletion.CASCADE, related_name='lamination', to='shablony_proschetov.templateprintcomponent', verbose_name='Компонент шаблона')),
            ],
            options={
                'verbose_name': 'Ламинация (шаблон)',
                'verbose_name_plural': 'Ламинации (шаблон)',
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Визитки", "Брошюры А4", "Меловка 350 г"', max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, default='', help_text='Необязательное текстовое пояснение к категории', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше категория в списке', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Оставьте пустым, чтобы создать корневую категорию', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shablony_proschetov.templatecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория шаблонов',
                'verbose_name_plural': 'Категории шаблонов',
            },
        ),
        migrations.CreateModel(
            name='TemplateAdditionalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Себестоимость, ₽')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Наценка, %')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена, ₽')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('formula_type', models.PositiveSmallIntegerField(choices=[(1, 'Фиксированная цена'), (2, 'Тираж × Цена (интерполяция по тиражу)'), (3, 'Цена × Тираж × (Количество резов × Коэффициент)'), (4, 'Количество листов × Цена × Количество резов (логарифмическая)'), (5, 'Количество изделий на листе × Цена × Количество листов'), (6, 'Количество изделий на листе × Цена × Тираж')], default=1, verbose_name='Формула расчёта')),
                ('lines_count', models.PositiveIntegerField(default=1, verbose_name='Количество линий реза')),
                ('items_per_sheet', models.PositiveIntegerField(default=1, verbose_name='Изделий на листе')),
                ('template_component', models.ForeignKey(help_text='Компонент, к которому относится эта работа', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='shablony_proschetov.templateprintcomponent', verbose_name='Компонент шаблона')),
                ('work', models.ForeignKey(blank=True, help_text='Ссылка на шаблон работы в справочнике', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_works', to='spravochnik_dopolnitelnyh_rabot.work', verbose_name='Работа из справочника')),
            ],
            options={
                'verbose_name': 'Дополнительная работа (шаблон)',
                'verbose_name_plural': 'Дополнительные работы (шаблон)',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='proschettemplate',
            name='category',
            field=models.ForeignKey(help_text='В какой ветке дерева лежит этот шаблон', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='shablony_proschetov.templatecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='proschettemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Пользователь, создавший шаблон', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='proschettemplate',
            name='source_proschet',
            field=models.ForeignKey(blank=True, help_text='Просчёт, из которого был создан шаблон (необязательно)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='calculator.proschet', verbose_name='Исходный просчёт'),
        ),
    ]
