# Generated by Django 4.2.7 on 2026-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shablony_proschetov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateadditionalwork',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название работы'),
        ),
    ]
