# Generated by Django 4.2.7 on 2025-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(db_column='order_number', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ready_datetime', models.DateTimeField(help_text='Когда должен быть готов заказ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
