# Generated by Django 4.2.7 on 2025-12-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('completed', 'Выдан')], default='accepted', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(verbose_name='Описание заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.AutoField(db_column='order_number', primary_key=True, serialize=False, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ready_datetime',
            field=models.DateTimeField(help_text='Когда должен быть готов заказ', verbose_name='Дата готовности'),
        ),
    ]
