# Generated by Django 4.2.7 on 2025-12-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название компании или ФИО', max_length=200, verbose_name='Название клиента')),
                ('phone', models.CharField(blank=True, help_text='Контактный телефон в формате +7 (XXX) XXX-XX-XX', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Электронная почта для связи', max_length=100, verbose_name='Email')),
                ('uses_edo', models.BooleanField(default=False, help_text='Отметьте, если с клиентом ведется электронный документооборот', verbose_name='Работает через ЭДО')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные сведения о клиенте', verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Используйте это поле, если клиента нет в базе данных', max_length=100, verbose_name='Имя клиента (ручной ввод)'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='counter_cli_name_3cade6_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['uses_edo'], name='counter_cli_uses_ed_a5c3df_idx'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Выберите клиента из базы данных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.client', verbose_name='Клиент'),
        ),
    ]
