# Generated by Django 4.2.7 on 2025-12-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_client_alter_order_customer_name_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(help_text='Выберите клиента из базы данных', null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.client', verbose_name='Клиент'),
        ),
    ]
